services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z
    container_name: minio
    ports:
      - "0.0.0.0:9000:9000"
      - "0.0.0.0:9009:9001"
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
      MINIO_DOMAIN: minio
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    networks:
      - minio-network

  createbuckets:
    image: quay.io/minio/mc:RELEASE.2025-03-12T17-29-24Z
    container_name: minio-createbuckets
    depends_on:
      - minio
    restart: on-failure
    networks:
      - minio-network
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set dockerminio http://minio:9000 admin adminadmin;
      /usr/bin/mc mb dockerminio/uploads;
      /usr/bin/mc mb dockerminio/backups;
      /usr/bin/mc mb dockerminio/documents;
      exit 0;
      "

volumes:
  minio_data:
    driver: local
  minio_config:
    driver: local

networks:
  minio-network:
    driver: bridge
